### PR TITLE
Added info that the signature itself also expires

### PR DESCRIPTION
**Pull request by ptorr-msft**
Will also update the batch file's comments.

### CODE REVIEW

**Comment by ptorr-msft** [comment]
Added some additional info to the `makecerts` batch file and the `readme` to make it clear that the *signature* will expire when the certificate expires (very useful for testing; potentially bad for production).

**Comment by Marv51** [comment]
I know this was merged quite a while ago. 

However, this is the only time I've ever seen these eku. Are there any other resource available on these? Cert with "1.3.6.1.5.5.7.3.3,1.3.6.1.4.1.311.10.3.13,1.3.6.1.4.1.311.76.5.200,1.3.6.1.4.1.311.76.5.300" as /eku is refused for me by VisualStudio. Am I doing it right?

@ptorr-msft

**Comment by ptorr-msft** [comment]
There used to be a Support article for this, but it's temporarily (?) out of action. It's the first hit for this search:

https://support.microsoft.com/search/results?query=object+ids+associated+with+Microsoft+cryptography

Hopefully the link will get fixed soon.

Did you use `makecert`? I don't know if it works in Visual Studio.

**Comment by Marv51** [comment]
Thank you for the reply! I was looking for that article before but as you said it is not available for now. I have extracted it from Google Cache (had to disable JS) now. That looks interesting, however, the eku's from from this patch are not documented there.

I have succeeded in creating a cert with makecert and using it with signtool to sign an msix(bundle). But unfortunatly I must have misunderstood, this cert seems to behave just the same as any other code signing cert. (The comments in this patch lead me to believe this might enable our app to be installable with sideloading disabled.)

Thanks for your help @ptorr-msft.

**Comment by ptorr-msft** [comment]
If you have sideloading disabled, apps must come from the Store; the EKUs won't help with that. Sorry.

**Pull request merged**
